// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"navbar\"><style>\n\t\t\t.navbar {\n\t\t\t\tdisplay: flex;\n\t\t\t\talign-items: center;\n\t\t\t\tjustify-content: space-between;\n\t\t\t\tpadding: 0 24px;\n\t\t\t\theight: 56px;\n\t\t\t\tborder-bottom: 1px solid #f0f0f0;\n\t\t\t\tbackground: #fff;\n\t\t\t}\n\t\t\t.navbar-brand {\n\t\t\t\tfont-size: 15px;\n\t\t\t\tfont-weight: 800;\n\t\t\t\tcolor: #111;\n\t\t\t\tletter-spacing: -0.02em;\n\t\t\t}\n\t\t\t.navbar-brand .accent {\n\t\t\t\tbackground: linear-gradient(135deg, #2563eb, #7c3aed);\n\t\t\t\t-webkit-background-clip: text;\n\t\t\t\t-webkit-text-fill-color: transparent;\n\t\t\t\tbackground-clip: text;\n\t\t\t}\n\t\t\t.navbar-links {\n\t\t\t\tdisplay: flex;\n\t\t\t\talign-items: center;\n\t\t\t\tgap: 24px;\n\t\t\t}\n\t\t\t.navbar-link {\n\t\t\t\tfont-size: 14px;\n\t\t\t\tcolor: #555;\n\t\t\t\ttext-decoration: none;\n\t\t\t\tfont-weight: 500;\n\t\t\t}\n\t\t\t.navbar-link:hover { color: #111; }\n\t\t</style><div class=\"navbar-brand\"><span class=\"accent\">templ</span>Book</div><div class=\"navbar-links\"><a class=\"navbar-link\" href=\"#getting-started\">Docs</a> <a class=\"navbar-link\" href=\"https://github.com\">GitHub</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
